### ISSUE TITLE
Better effect labels

### ISSUE THREAD

**Issue by lektu** [NeV3rKilL/alien-actions#2]
Currently, when the cursor hovers over a token's status effects list, the tooltip for this module's statuses shows as "EFFECT.StatusFastAction" and "EFFECT.StatusSlowAction". That's kind of ugly; other statuses are shown with normal English names.

Wouldn't it be better to just use "Fast Action" and "Slow Action"?

```
  CONFIG.statusEffects.push({
    "id": "fastAction",
    "label": "Fast Action",
    "icon": "modules/alien-actions/assets/fastaction.svg"
  });

  CONFIG.statusEffects.push({
    "id": "slowAction",
    "label": "Slow Action",
    "icon": "modules/alien-actions/assets/slowaction.svg"
  });

```

**Comment by Gorvaine** [comment]
Pushed on 1.5.1
