### ISSUE TITLE
Incompatibility with CUB

### ISSUE THREAD

**Issue by danielmacapa** [NeV3rKilL/alien-actions#3]
hello, when installing CUB (Combat Utility Belt), the macros stop working. Is there a solution?

**Comment by Gorvaine** [comment]
CUB is changing effect name's when the option "Remove Default Status Effects".

It does not only  break macros, it breaks the effects being removed at the end of rounds too.

As a solution I recommend to disable this option on the CUB config menu while a compatibility update is baked.

**Comment by Gorvaine** [comment]
Should be fixed on https://github.com/NeV3rKilL/alien-actions/releases/tag/1.5.2
